os: linux 
arch: arm64 
dist: bionic
language: python

addons:
  apt:
    packages:
      - wayland-protocols
      - ninja-build
      - libwayland-dev

install:
  - pip install meson

script:
  - meson build
  - ninja -C build
  - meson test -C build
