os: linux 
arch: arm64 
dist: bionic
language: minimal

addons:
  apt:
    packages:
      - meson
      - wayland-protocols
      - ninja-build
      - libwayland-dev

script:
  - meson build
  - ninja -C build
  - meson test -C build
