dist: xenial
language: minimal

env:
  DOCKER_IMAGE: francma/wob-travis-ci
  DOCKER_CWD: /wob
  BUILD_DIR: build

services:
  - docker

script:
  - docker run -v "$PWD":"$DOCKER_CWD" -w "$DOCKER_CWD" "$DOCKER_IMAGE" /usr/bin/meson "$BUILD_DIR" --buildtype release
  - docker run -v "$PWD":"$DOCKER_CWD" -w "$DOCKER_CWD" "$DOCKER_IMAGE" /usr/bin/ninja -C "$BUILD_DIR"